/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeliveryPerson } from "./DeliveryPerson";
import { DeliveryPersonCountArgs } from "./DeliveryPersonCountArgs";
import { DeliveryPersonFindManyArgs } from "./DeliveryPersonFindManyArgs";
import { DeliveryPersonFindUniqueArgs } from "./DeliveryPersonFindUniqueArgs";
import { DeleteDeliveryPersonArgs } from "./DeleteDeliveryPersonArgs";
import { DeliveryPersonService } from "../deliveryPerson.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DeliveryPerson)
export class DeliveryPersonResolverBase {
  constructor(
    protected readonly service: DeliveryPersonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DeliveryPerson",
    action: "read",
    possession: "any",
  })
  async _deliveryPeopleMeta(
    @graphql.Args() args: DeliveryPersonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DeliveryPerson])
  @nestAccessControl.UseRoles({
    resource: "DeliveryPerson",
    action: "read",
    possession: "any",
  })
  async deliveryPeople(
    @graphql.Args() args: DeliveryPersonFindManyArgs
  ): Promise<DeliveryPerson[]> {
    return this.service.deliveryPeople(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DeliveryPerson, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DeliveryPerson",
    action: "read",
    possession: "own",
  })
  async deliveryPerson(
    @graphql.Args() args: DeliveryPersonFindUniqueArgs
  ): Promise<DeliveryPerson | null> {
    const result = await this.service.deliveryPerson(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DeliveryPerson)
  @nestAccessControl.UseRoles({
    resource: "DeliveryPerson",
    action: "delete",
    possession: "any",
  })
  async deleteDeliveryPerson(
    @graphql.Args() args: DeleteDeliveryPersonArgs
  ): Promise<DeliveryPerson | null> {
    try {
      return await this.service.deleteDeliveryPerson(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
